### PR TITLE
Remove mock auth server support

### PR DESCRIPTION
**Pull request by djmitche**
Now that createSignatureValidator is an internal part of the tc-auth
package, this package cannot use it.  The fakeauth functionality is
already available, and much simpler to use, without losing any
resolution in tests.

See
- https://github.com/taskcluster/taskcluster-auth/pull/39
- https://github.com/taskcluster/taskcluster-lib-api/pull/9

### CODE REVIEW

**Comment by djmitche** [comment]
I think this should ship with a major version bump for the library, so that existing packages can continue using the mock auth server until they're ready to update.

**Comment by jonasfj** [comment]
`r+` but as I mentioned before migration will be a pain...

btw, I agree with major version bump... But since this haven't reached `1.0.0` yet, that means `0.10.0` is the next version...

**Comment by djmitche** [comment]
Will "^0.9.1" safely not pull 0.10.0?

**Comment by jonasfj** [comment]
> Will "^0.9.1" safely not pull 0.10.0?

Yes, also the definition of semver is that until `1.0.0` you can break API between minor releases...

Granted, I guess it would be cool if we had verison `10.0.0`, he he :)

**Comment by jonasfj** [comment]
http://semver.org/#spec-item-4

**Comment by jonasfj** [comment]
Actually, we should probably consider want we want to fix before just moving to 1.0.0 for all our libs...

**Comment by djmitche** [comment]
If npm's implementation of semver really ignores compatibility for 0._, then yes, we should move to 1._.  I don't want to ship this and find subsequent deployments in heroku failing because 0.9.0 got pulled when it shouldn't have.  To that end, maybe this is the right time to go to 1.0?

**Comment by jonasfj** [comment]
`^0.1.0` in npm is afaik `0.1.0`  is `0.1.x`, but not `0.2.x`. 
So `0.10.0` is perfectly fine...

This is a bike-shedding thing... but I note that we've broken compatibility 10 times... so we're likely to it again... especially in this component... api, client, config and loader might be more like a 1.0.
But -lib-testing is really a collection of hacks... At least at this point. (look at what it does for pulse).

**Pull request merged**
